### ISSUE TITLE
"default_dashboard" setting

### ISSUE THREAD

**Issue by Geolim4** [marcin-jozwikowski/easy-admin-pretty-urls#37]
Hello Marcin 😂

I have another request for you:

I recently developed a new area of my easy admin project:

A `/volunteer` area for people with very low access and few dedicated controllers.

Everything is working well except one thing:

```yml
pretty_routes_admin:
    resource: 'src/Controller/Admin'
    type: 'pretty_routes'
    prefix: /admin

pretty_routes_volunteer:
    resource: 'src/Controller/Volunteer'
    type: 'pretty_routes'
    prefix: /espace-benevole
```

The routes are well rewritten, except I'm getting the Dashboard menu from my Admin area due to this settings:
`default_dashboard`

I think that you should give the (optional) ability to set a custom dasboard inside the `PrettyRoutesController` attribute, something like:

```php
#[PrettyRoutesController(path: 'candidats', dasboard: YourDashboardClass:class)]
```

If the **dasboard** parameter is set then your code use it, then it fallback to the "default_dashboard" settings. 

What do you think of it ?
